apiVersion: apps/v1
kind: Deployment
metadata:
  name: languages-app-consume-events-deployment
  labels:
    app: languages-app
    role: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: languages-app-consume-events-deployment
  template:
    metadata:
      labels:
        app: languages-app-consume-events-deployment
    spec:
      containers:
        - name: app-consume-events-deployment
          image: mapeveri/languages:latest
          command: ["npm", "run", "consumer:domain-events"]
          envFrom:
            - configMapRef:
                name: languages-app-config-map
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: languages-app-secret
                  key: GOOGLE_CLIENT_ID
            - name: POSTGRESQL_DB_URL
              valueFrom:
                secretKeyRef:
                  name: languages-app-secret
                  key: POSTGRESQL_DB_URL
          volumeMounts:
            - name: languages-secret-volume
              mountPath: /etc/languages/secret
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: languages-secret-volume
          secret:
            secretName: languages-app-secret
