apiVersion: apps/v1
kind: Deployment
metadata:
  name: languages-app-deployment
  labels:
    app: languages-app
    role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: languages-app-deployment
  template:
    metadata:
      labels:
        app: languages-app-deployment
    spec:
      containers:
        - name: app
          image: mapeveri/languages:latest
          envFrom:
            - configMapRef:
                name: languages-app-config-map
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: languages-app-secret
                  key: GOOGLE_CLIENT_ID
            - name: POSTGRESQL_DB_URL
              valueFrom:
                secretKeyRef:
                  name: languages-app-secret
                  key: POSTGRESQL_DB_URL
          volumeMounts:
            - name: languages-secret-volume
              mountPath: /etc/languages/secret
              readOnly: true
          ports:
            - containerPort: 4000
      restartPolicy: Always
      volumes:
        - name: languages-secret-volume
          secret:
            secretName: languages-app-secret
        - name: app-storage
          persistentVolumeClaim:
            claimName: languages-app-pvc
