apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: languages-app-api-pvc
  labels:
    app: languages-app
    role: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
