apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o .k8s
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/typescript-ddd-cqrs-default: "true"
    io.kompose.service: app
  name: app
spec:
  containers:
    - image: mapeveri/languages:latest
      name: languages-container
      envFrom:
        - configMapRef:
            name: app-config
      ports:
        - containerPort: 4000
          hostPort: 4000
          protocol: TCP
      resources: {}
  restartPolicy: Always
  volumes:
    - name: env-file
      configMap:
        name: app-config
        items:
          - key: .env
            path: .env
status: {}
