apiVersion: apps/v1
kind: Deployment
metadata:
  name: languages-app-api-deployment
  labels:
    app: languages-app
    role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: languages-app-api
  template:
    metadata:
      labels:
        app: languages-app-api
    spec:
      containers:
        - name: app
          image: mapeveri/languages:latest
          envFrom:
            - configMapRef:
                name: languages-app-config-map
            - secretRef:
                name: languages-app-secret
          ports:
            - containerPort: 4000
      restartPolicy: Always
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: languages-app-pvc
