apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: db-claim0
  labels:
    role: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
