apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: mongo1-service
    role: database
  name: mongo1
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    name: mongo1
status:
  loadBalancer: {}
