apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: mongo1-deployment
    role: database
  name: mongo1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mongo1
    spec:
      containers:
        - args:
            - --bind_ip_all
            - --replSet
            - rs0
          image: mongo:6
          name: mongo1
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo1-claim0
      restartPolicy: Always
      volumes:
        - name: mongo1-claim0
          persistentVolumeClaim:
            claimName: mongo1-claim0
status: {}
