apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: mongo1-deployment
    role: database
  name: mongo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo1
    spec:
      containers:
        - name: mongo1
          image: mongo:6
          command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo1-claim0
              mountPath: /data/db
      volumes:
        - name: mongo1-claim0
          persistentVolumeClaim:
            claimName: mongo1-claim0
  strategy: {}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
spec:
  template:
    spec:
      containers:
        - name: mongodb-init
          image: mongo:6
          command:
            - "/bin/bash"
            - "-c"
            - |
              #!/bin/bash
              echo "Mongo init"
              sleep 30
              mongosh --host mongo1:27017 <<EOF
                cfg = {
                  "_id": "rs0",
                  "members": [
                    { "_id": 0, "host": "mongo1:27017" }
                  ]
                };
                rs.initiate(cfg);
              EOF
      restartPolicy: OnFailure
