apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: rabbitmq
    role: message-broker
  name: rabbitmq
spec:
  ports:
    - name: "5630"
      port: 5630
      targetPort: 5672
    - name: "8090"
      port: 8090
      targetPort: 15672
  selector:
    name: rabbitmq
status:
  loadBalancer: {}
