version: '3.2'
services:
  app:
    image: languages
    container_name: languages-container
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/languages
    ports:
      - "4000:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./docker/data/mongodata:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh mongodb:27017/test --quiet"] 
      interval: 10s
      timeout: 5s
      retries: 3
