name: App CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run linter
        run: npm run linter
      - name: Run format-code
        run: npm run format-code
      - name: Run tests
        run: npm run test
